DROP DATABASE IF EXISTS next_venture_db;
CREATE DATABASE next_venture_db;

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;


CREATE TABLE user (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(150) NOT NULL UNIQUE,
first_name VARCHAR(150) NOT NULL,
last_name VARCHAR(150) NOT NULL,
password VARCHAR(150) NOT NULL,
date_created TIMESTAMP DEFAULT NOW(),
last_visit TIMESTAMP DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE game_preferences (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
name VARCHAR(150),
FOREIGN KEY (user_id) REFERENCES users(id)
);
